[package]
name = "loa"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
colorex = "0.1.0"
lexer = { path = "./lexer" }
parser = { path = "./parser" }
codegen = { path = "./codegen" }

[workspace]
members = [
    "lexer",
    "parser",
    "error",
    ".", "codegen",
]

